"""Story model — tiered narrative arcs."""

from __future__ import annotations

from enum import StrEnum
from typing import Self

import aiosqlite
from pydantic import BaseModel, Field

from charlieverse.memory.sessions import SessionId
from charlieverse.types.dates import UTCDatetime, from_iso, from_iso_or_none, utc_now
from charlieverse.types.id import ModelId
from charlieverse.types.lists import TagList, decode_tag_list
from charlieverse.types.strings import MediumDescription, NonEmptyString, ShortDescription, ShortString


class StoryId(ModelId):
    pass


class StoryTier(StrEnum):
    session = "session"
    daily = "daily"
    weekly = "weekly"
    monthly = "monthly"
    quarterly = "quarterly"
    yearly = "yearly"
    all_time = "all-time"


class Story(BaseModel):
    """A tiered narrative arc generated by the Storyteller."""

    id: StoryId
    title: ShortString
    summary: ShortDescription | None
    content: MediumDescription
    tier: StoryTier
    period_start: str | None
    period_end: str | None
    workspace: NonEmptyString | None
    session_id: SessionId | None
    tags: TagList | None
    created_at: UTCDatetime
    updated_at: UTCDatetime
    deleted_at: UTCDatetime | None

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    @classmethod
    def from_row(cls, row: aiosqlite.Row) -> Self:
        return cls.model_construct(
            id=StoryId(row["id"]),
            title=row["title"],
            summary=row["summary"],
            content=row["content"],
            tier=StoryTier(row["tier"]),
            period_start=row["period_start"],
            period_end=row["period_end"],
            workspace=row["workspace"],
            session_id=SessionId(row["session_id"]) if row["session_id"] else None,
            tags=decode_tag_list(row["tags"]),
            created_at=from_iso(row["created_at"]),
            updated_at=from_iso(row["updated_at"]),
            deleted_at=from_iso_or_none(row["deleted_at"]),
        )

    @property
    def embed_content(self) -> str:
        return f"{self.title}\n{f'\n{self.summary}' or ''}{self.content}"


class NewStory(BaseModel):
    """Payload for creating a new story."""

    id: StoryId = Field(default_factory=StoryId)
    title: ShortString
    summary: ShortDescription | None = None
    content: MediumDescription
    tier: StoryTier
    period_start: str | None = None
    period_end: str | None = None
    workspace: NonEmptyString | None = None
    session_id: SessionId | None = None
    tags: TagList | None = None
    created_at: UTCDatetime = Field(default_factory=utc_now)


class UpdateStory(BaseModel):
    """Payload for updating an existing story."""

    id: StoryId
    title: ShortString
    summary: ShortDescription | None = None
    content: MediumDescription
    tier: StoryTier
    period_start: str | None = None
    period_end: str | None = None
    workspace: NonEmptyString | None = None
    session_id: SessionId | None = None
    tags: TagList | None = None
    updated_at: UTCDatetime = Field(default_factory=utc_now)


class DeleteStory(BaseModel):
    id: StoryId
    deleted_at: UTCDatetime = Field(default_factory=utc_now)
